### ISSUE TITLE
I found out that my EC registers is just the same as yours.

### ISSUE THREAD

**Issue by edward-p** [atharvalele/MSI_Fan_Control#1]
My laptop is MSI GP62 6QG
And I found 0x98 controls the "cooler boost"

|value|cooler boost|
|------|--------------|
|0x02|off|
|0x82|on|

**Comment by atharvalele** [comment]
Thank you for informing me. I'll add these to the script.

Are you using the script? And if so, is it working properly?

**Comment by edward-p** [comment]
Got some troubles.

It seems that I can only read `/sys/kernel/debug/ec/ec0/io`, even I have added `ec_sys.write_support=1` as kernel parameter.

I've tried dump  the `/sys/kernel/debug/ec/ec0/io` with `xxd`, manually edit the dump, then reverse it to `/sys/kernel/debug/ec/ec0/io`, nothing changes.

https://asciinema.org/a/Fv8KGpVmwhtr1lTRQh2LdloxC

It should't be the problem of your script.

btw: there is a similar project just like yours [YoyPa/isw](https://github.com/YoyPa/isw)

**Comment by atharvalele** [comment]
Oh alright. I'll see if I have the same issue or not, because the script wouldn't work after waking the laptop from suspend mode. It would work on a clean boot though.

That project seems more complete than mine. I haven't had the time to work on this for a while.

**Comment by edward-p** [comment]
It's okay.
I'll try to figure out why I can't write into `/sys/kernel/debug/ec/ec0/io` myself.

**Comment by edward-p** [comment]
> It's okay.
> I'll try to figure out why I can't write into `/sys/kernel/debug/ec/ec0/io` myself.

Finnally, I found out `0xf4` controls the Fan Mode:

|Value|Fan Mode|
|-------|--------------|
|0x0c|Auto|
|0x4c|Basic|
|0x8c|Advanced|

The default mode of My Laptop on start up is set to `0x0c` for `Auto Mode`.
I have to write `0x8c` into `0xf4` to enable `Avanced Mode` first.
Then I will be able to control fan speed by setting up `0x72-0x78`, other wise those data will be overwritten by EC itself under `Auto Mode` (It just acts like I don't have write access of `/sys/kernel/debug/ec/ec0/io` :rofl: ).
Now things are more clear. After you  waking the laptop from suspend mode,  `0xf4`  is set to `0x0c` for `Auto Mode`, I guess.

**Comment by atharvalele** [comment]
Aha! Thank you! That's a nice find.
